PKG_SOURCE_URL:=https://github.com/mkschreder/libk.git
PKG_SOURCE_VERSION:=d6399620797213b1ea5a7a432cf00abc2d01fa77

define Package/info
	DEPENDS:=package/libfreertos
	LDFLAGS+=
endef 

define Package/install
	$(INSTALL_DIR) $(2)/usr/lib/
	$(CP) $(1)/src/.libs/libk.a $(2)/usr/lib/
	$(INSTALL_DIR) $(2)/usr/include/libk/
	(cd $(1)/src/ && find . -name '*.h' -print | tar --create --files-from -) | (cd $(2)/usr/include/libk/ && tar xfp -) 
endef

$(eval $(call BuildPackage,libk))
