PKG_SOURCE_URL:=https://github.com/mkschreder/libk-freertos.git
PKG_SOURCE_VERSION:=78c82950e2557cd97d05d4ce8e3b71045d177585

define Package/info
	DEPENDS+=
	LDFLAGS+=
endef

define Package/install
	$(INSTALL_DIR) $(2)/usr/lib/
	$(CP) $(1)/src/.libs/libfreertos.a $(2)/usr/lib/
	$(INSTALL_DIR) $(2)/usr/include/freertos/
	(cd $(1)/src/ && find . -name '*.h' -print | tar --create --files-from -) | (cd $(2)/usr/include/freertos/ && tar xfp -) 
endef

$(eval $(call BuildPackage,libfreertos))
