define module/block/at24 
	MAINTAINER:=Martin K. Schröder <mkschreder.uk@gmail.com>"
	DESCRIPTION:=AT24 SPI flash module
endef

$(eval $(call BuildModule,at24,at24.c))

define module/block/m25p16 
	MAINTAINER:=Martin K. Schröder <mkschreder.uk@gmail.com>"
	DESCRIPTION:=m25p16 SPI flash module
endef

$(eval $(call BuildModule,m25p16,serial_flash.c))

docs-y += block/README.md
