#build-imx233-demo: build
#	$(CC) $(CFLAGS) -c examples/imx233-demo/imx233-demo.c -o examples/imx233-demo/imx233-demo.o
#	$(CC) -L$(srctree) $(LDFLAGS) -o examples/imx233-demo/imx233-demo -Wl,--start-group \
#		  -lk-$(BUILD) -lc -lm -lgcc examples/imx233-demo/imx233-demo.o \
#	-Wl,--end-group 
obj-y += examples/imx233-demo/imx233-demo.o
