PKG_SOURCE_URL:=https://github.com/mkschreder/libu8gfx.git
PKG_SOURCE_VERSION:=7e5158ae08b2154b1ac1ed0acc5ebf720ca2ae84

define Package/install
	$(INSTALL_DIR) $(2)/usr/lib/
	$(CP) $(1)/src/.libs/libu8gui.a $(2)/usr/lib/
	$(INSTALL_DIR) $(2)/usr/include/u8gfx/
	(cd $(1)/src/ && find . -name '*.h' -print | tar --create --files-from -) | (cd $(2)/usr/include/u8gfx/ && tar xfp -) 
endef

$(eval $(call BuildPackage,libu8gfx))
