obj-$(CONFIG_ILI9340) += disp/ili9340.o 
obj-$(CONFIG_LCDPAR) += disp/lcd.o 
obj-$(CONFIG_LEDMATRIX88) += disp/ledmatrix88.o 
obj-$(CONFIG_SEVSEG) += disp/lcd7seg.o 
obj-$(CONFIG_SSD1306) += disp/ssd1306.o
obj-$(CONFIG_KS0713) += disp/ks0713.o
obj-$(CONFIG_DISP_GENERIC_TEXT) += disp/text.o 

docs-y += disp/README.md
