obj-$(CONFIG_FREERTOS) += \
	kernel/freertos/croutine.o \
	kernel/freertos/event_groups.o \
	kernel/freertos/list.o \
	kernel/freertos/queue.o \
	kernel/freertos/tasks.o \
	kernel/freertos/timers.o \
	kernel/freertos/memory/heap_1.o 

include kernel/freertos/portable/Makefile
