obj-$(CONFIG_FREERTOS) += \
	kernel/freertos/croutine.o \
	kernel/freertos/event_groups.o \
	kernel/freertos/list.o \
	kernel/freertos/queue.o \
	kernel/freertos/tasks.o \
	kernel/freertos/timers.o \
	kernel/freertos/heap_3.o \
	kernel/freertos/port.o 
