obj-y += kernel/main.o
obj-y += kernel/thread/async.o
obj-y += kernel/thread.o
obj-y += kernel/cbuf.o
obj-y += kernel/io_device.o
obj-y += kernel/gbuf.o

docs-y += kernel/README.md

include kernel/dev/Makefile
