obj-$(CONFIG_BOARD_MULTIWII) += boards/multiwii.o
obj-$(CONFIG_BOARD_RXTX) += boards/promini_rxtx.o
obj-$(CONFIG_BOARD_STM32F103) += boards/stm32f103.o
obj-$(CONFIG_BOARD_ARDUINO_DUE) += boards/arduino_due.o

