obj-$(CONFIG_BOARD_STM32F103) += boards/stm32f103.o
obj-$(CONFIG_BOARD_ARDUINO_DUE) += boards/arduino/arduino_due.o
obj-$(CONFIG_ATMEGA328P) += boards/arduino/promini.o

include boards/flight_control/Makefile
