obj-$(CONFIG_SAM3) += boards/arduino/arduino_due.o
obj-$(CONFIG_ATMEGA328P) += boards/arduino/promini.o 

docs-y += boards/README.md

include boards/flight_control/Makefile
include boards/rc/Makefile
include boards/imx233/Makefile 
