
docs-y += examples/README.md

#include examples/hello_world/Makefile
#include examples/fst6-demo/Makefile
#include examples/fst6-gui/Makefile
#include examples/cc3d-demo/Makefile
#include examples/mwii-demo/Makefile
include examples/native-demo/Makefile
