PKG_SOURCE_URL:=https://github.com/mkschreder/libm2gui.git
PKG_SOURCE_VERSION:=eea1195ef1ffdc3d9e48426e79283fe3b29ef6f8

define Package/install
	$(INSTALL_DIR) $(2)/usr/lib/
	$(CP) $(1)/src/.libs/libm2gui.a $(2)/usr/lib/
	$(INSTALL_DIR) $(2)/usr/include/m2gui/
	(cd $(1)/src/ && find . -name '*.h' -print | tar --create --files-from -) | (cd $(2)/usr/include/m2gui/ && tar xfp -) 
endef

$(eval $(call BuildPackage,libm2gui))
