obj-$(CONFIG_APP_print_hello) += apps/print-hello.o
obj-$(CONFIG_APP_imx23_ssd1306) += apps/imx23-ssd1306.o
obj-$(CONFIG_APP_test) += apps/test.o
obj-$(CONFIG_APP_RTOS_TEST) += apps/rtos-test.o
LDFLAGS-$(CONFIG_APP_test) += -lpthread
