obj-$(CONFIG_APP_print_hello) += apps/print-hello.o
obj-$(CONFIG_APP_imx23_ssd1306) += apps/imx23-ssd1306.o
obj-$(CONFIG_APP_test) += apps/test.o
obj-$(CONFIG_APP_RTOS_TEST) += apps/rtos-test.o
obj-$(CONFIG_ARDUINO_PWM_BLINK_THREAD) += apps/arduino/pwm_blink_and_input.o
obj-$(CONFIG_ARDUINO_EXTERNAL_RTC_EEPROM) += apps/arduino/i2c_external_rtc.o
LDFLAGS-$(CONFIG_APP_test) += -lpthread
