#obj-y += net/uip/psock.o  net/uip/uip_arp.o  net/uip/uip-fw.o  net/uip/uip-neighbor.o net/uip/timer.o  net/uip/uip.o      net/uip/uiplib.o  net/uip/uip-split.o
#obj-n += net/lwip/def.o   net/lwip/init.o  net/lwip/netif.o  net/lwip/stats.o  net/lwip/tcp_in.o   net/lwip/udp.o net/lwip/dhcp.o    net/lwip/pbuf.o   net/lwip/sys.o    net/lwip/tcp_out.o net/lwip/dns.o    net/lwip/raw.o    net/lwip/tcp.o    net/lwip/timers.o
#obj-n +=  net/lwip/mem.o  net/lwip/memp.o
#obj-n += net/lwip/ipv4/autoip.o  net/lwip/ipv4/igmp.o  net/lwip/ipv4/inet_chksum.o  net/lwip/ipv4/ip.o net/lwip/ipv4/icmp.o    net/lwip/ipv4/inet.o  net/lwip/ipv4/ip_addr.o      net/lwip/ipv4/ip_frag.o
INCLUDES += -Iinclude/ipv4/

#obj-$(CONFIG_DHCP) += dhcp.o 
#obj-$(CONFIG_DNS) += dns.o 
obj-$(CONFIG_ENC28J60) += net/enc28j60.o 
#obj-$(CONFIG_RFNET) += rfnet.o 
#obj-$(CONFIG_TCPIP) += tcpip.o 
