PKG_SOURCE_URL:=https://github.com/mkschreder/libblobpack.git
PKG_SOURCE_VERSION:=0d1db44094ba49a0ca51e675f80d79efe5551cbd

define Package/install
	$(INSTALL_DIR) $(2)/usr/lib/
	$(CP) $(1)/src/.libs/libblobpack.a $(2)/usr/lib/
	$(INSTALL_DIR) $(2)/usr/include/blobpack/
	$(CP) $(1)/src/*.h $(2)/usr/include/blobpack/
endef

$(eval $(call BuildPackage,libblobpack))
